<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>jep_construction_api</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="Dapper" Version="2.1.66" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.36" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.36" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.36">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.36" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.2" />
		<PackageReference Include="PusherServer" Version="4.6.1" />
		<PackageReference Include="RestSharp" Version="107.3.0" />
		<PackageReference Include="Synology.NET" Version="1.0.2" />
		<PackageReference Include="SynologyDotNet.Core" Version="0.3.0" />
		<PackageReference Include="System.Drawing.Common" Version="5.0.2" />
		<PackageReference Include="TimeZoneConverter" Version="3.5.0" />
		<PackageReference Include="Twilio" Version="5.61.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

</Project>
